version: '3.1'

services:

  nginx:
    build:
      context: ./
      dockerfile: docker/nginx.docker
    volumes:
      - ./:/var/www
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - php-fpm
      - db
  php-fpm:
    build:
      context: ./
      dockerfile:  docker/php-fpm.docker
    volumes:
      - ./:/var/www
    user: 1000:1000
    expose:
      - 9000
    environment:
      DB_HOST: ${DB_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PORT_PG: ${PORT_PG}
    depends_on:
      - db

  db:
    image: postgres:10
    restart: always
    ports:
      - 5432:5432
#    volumes:
#      - ./docker/storage/postgresql:/data/postgres
    environment:
      DB_HOST: ${DB_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}

  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - 8080:8080