version: '3.1'

services:

  nginx:
    build:
      context: ./
      dockerfile: docker/nginx.docker
    volumes:
      - ./:/var/www/html
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    depends_on:
      - php-fpm
  php-fpm:
    build:
      context: ./
      dockerfile:  docker/php-fpm.docker
    volumes:
      - ./:/var/www/html
    user: 1000:1000
    restart: on-failure
    expose:
      - 9000
#    environment:
#      MAIL: ${MAIL}
#      MAIL_PASSWORD: ${MAIL_PASSWORD}
#      WEBHOOK: ${WEBHOOK}
